### ISSUE TITLE
Cleanup script issues: "keypair already exists" exceptions

### ISSUE THREAD

**Issue by slaki** [telefonicaid/fiware-health#15] opened 2015-03-12 14:22 UTC
Dear Fernando,

We saw the following errors in the sanity check that may be related to the script and not to the node:
1. Key pair \'testing_keypair06\' already exists. (HTTP 409)
2. Quota exceeded for instances: Requested 1, but already used 3 of 3 instances (HTTP 413)
3. Key pair 'testing_keypair04' already exists. (HTTP 409)

For me it seems that some cleanup scripts don't work properly. Since the keypairs should be deleted before testing the creation, etc...
Could you please have a look at it?

The issue is related to Budapest node...

Best,
Sandor

**Comment by flopezag** [comment] 2015-03-26 10:32
We are cleaning every day the different results of the Validation Test in order that this problem will not reproduce again. Nevertheless, we have planned a User Story for the next sprint in order to resolve any problem with data when a error is detected in one node and some resources stay consequently on it.

Best regards,
Fernando

**Comment by seanrmurphy** [comment] 2015-04-08 07:33
We have seen something similar relating to the security groups - today we had an issue that in the test_deploy_instance_with_new_network_and_sec_group test, it was trying to use a secgroup which already exists - Multiple security_group matches found for name 'testing_sec_group_05'. We think this arises from problems in previous cleanup.

Maybe when these cleanup issues are resolved, it would be good to have either a set of instructions or a small script to perform a once-off clean up to make sure the system is in a good state to run the tests.

**Comment by flopezag** [comment] 2015-04-15 05:39
I hope that the PR #29 will resolve this issue since today, we can check it and close the issue.

**Closed as completed** 2015-04-22 13:30 UTC
